fix asus spidering
fkie-cad/FirmwareScraper pull request #1
Opened 2021-12-15 19:05 UTC by armijnhemel

Apparently ASUS reworked their website. This PR should fix that.

2021-12-22 08:29 UTC, rhelmke commented
Hey Armijn,

apologies. As we just recently migrated this repo into our organisation, we forgot to set up notifications. I'm going to check this PR in the near future. :-)

2021-12-23 13:32 UTC, rhelmke requested changes
Hey, thank you so much for your contribution!

I tested your fix, and it works. There are a few minor changes I'd like to see in your code. Then I'm happy to pull in the changes.

Unfortunately, this fix can only be temporary, as I've noticed that the scraper does not pull in all firmware images. For example, images for the `TUF-AX5400` are missing. I am not sure why this happens. Of course we'd be grateful if you can fix this. Otherwise, we'll create an internal issue and check it out some time early in the next year.

Cheers and happy holidays

2021-12-23 13:32 UTC, rhelmke commented on firmware/spiders/asus.py
> +import re
```suggestion
from re import findall
```
You can not know that, but we prefer pulling in the methods we use into the file's root namespace. If that is okay, please consider accepting my suggestion here :-)

2021-12-23 13:32 UTC, rhelmke commented on firmware/spiders/asus.py
> +           url_redirects.update(re.findall('"url": "(https://[\w\d\-\_\./]+)"', header))
```suggestion
           url_redirects.update(findall(r'"url": "(https://[\w\d\-\_\./]+)"', header))
```
Can you please use the `r`-prefix for regex patterns? Also, we would strike the `re`-namespace due to the change above.

2021-12-23 13:32 UTC, rhelmke commented on firmware/spiders/asus.py
> +           url_redirects.update(re.findall('"url": "(https://[\w\d\-\_\./]+)"', header))
```suggestion
            if not '"url"' in header:
                continue
            url_redirects.update(re.findall('"url": "(https://[\w\d\-\_\./]+)"', header))
```
There is mixed indentation here.

2021-12-23 13:38 UTC, armijnhemel commented
> Hey, thank you so much for your contribution!
> 
> I tested your fix, and it works. There are a few minor changes I'd like to see in your code. Then I'm happy to pull in the changes.
> 
> Unfortunately, this fix can only be temporary, as I've noticed that the scraper does not pull in all firmware images. For example, images for the `TUF-AX5400` are missing. I am not sure why this happens. Of course we'd be grateful if you can fix this. Otherwise, we'll create an internal issue and check it out some time early in the next year.

I think this is because ASUS probably changed the format of the website. I need to look into this.

Personally I am also interested in any of the source code archives that are published so I am thinking of downloading those as well. I am not sure if you want to crawl these as well.

2021-12-23 13:39 UTC, armijnhemel commented on firmware/spiders/asus.py
> +           url_redirects.update(re.findall('"url": "(https://[\w\d\-\_\./]+)"', header))
Urgh. Fixed.

2021-12-23 13:45 UTC, rhelmke commented
> Personally I am also interested in any of the source code archives that are published so I am thinking of downloading those as well. I am not sure if you want to crawl these as well.

Are you refering to the GPL sources? We'd be interested in them as well. Maybe it is possible to include the feature in a non-invasive way that allows easy enabling/disabling.

2022-01-13 11:11 UTC, rhelmke reviewed
Hey Armijn, happy new year!

We are planning to verify each spider internally. Thus, we will probably rework the ASUS one as well. Are there any updates from your side? If not, I'd suggest we merge this PR now.

2022-01-13 12:59 UTC, armijnhemel commented
> Hey Armijn, happy new year!
> 
> We are planning to verify each spider internally. Thus, we will probably rework the ASUS one as well. Are there any updates from your side? If not, I'd suggest we merge this PR now.

No updates here!

2022-01-13 13:45 UTC, merged

2022-01-13 13:45 UTC, rhelmke commented
Alrighty, thanks for the feedback!